/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BodyEntries {
  client_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  d: string;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  seq: Int8;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  version: Generated<number>;
  weight_lb: Numeric;
  wk: string;
}

export interface Config {
  client_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  data: Json;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  schema_version: Generated<number>;
  seq: Int8;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  version: Generated<number>;
}

export interface LibraryItems {
  client_id: string;
  client_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  data: Json;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  schema_version: Generated<number>;
  seq: Int8;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  version: Generated<number>;
}

export interface ListItems {
  client_id: string;
  client_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  data: Json;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  list: string;
  position: number;
  schema_version: Generated<number>;
  seq: Int8;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  version: Generated<number>;
}

export interface LogEntries {
  auto: Generated<boolean>;
  client_id: string;
  client_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  d: string;
  deleted_at: Timestamp | null;
  exercise_id: string;
  hold_sec: Numeric | null;
  id: Generated<Int8>;
  note: string | null;
  phase: string | null;
  reps: Numeric | null;
  seq: Int8;
  sets: Json | null;
  sets_count: number | null;
  slot: string | null;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  version: Generated<number>;
  weight_lb: Numeric | null;
  wk: string | null;
}

export interface Programs {
  client_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  data: Json;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  key: string;
  schema_version: Generated<number>;
  seq: Int8;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  version: Generated<number>;
}

export interface RefusedWrites {
  client_id: string | null;
  client_version: string | null;
  command: string;
  id: Generated<Int8>;
  payload: Json | null;
  reason: string;
  received_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface RowHistory {
  data: Json;
  id: Generated<Int8>;
  replaced_at: Generated<Timestamp>;
  row_id: Int8;
  table_name: string;
  user_id: Int8;
  version: number;
}

export interface StretchWeeks {
  client_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  data: Json;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  schema_version: Generated<number>;
  seq: Int8;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  version: Generated<number>;
  week_start: string;
}

export interface SupplementDays {
  boost: Json | null;
  client_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  day: string;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  seq: Int8;
  taken: Generated<Json>;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  version: Generated<number>;
  water: Generated<Json>;
}

export interface Users {
  auth_user_id: string;
  change_seq: Generated<Int8>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  is_admin: Generated<boolean>;
}

export interface Weeks {
  client_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  data: Json;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  schema_version: Generated<number>;
  seq: Int8;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  version: Generated<number>;
  week_start: string;
}

export interface DB {
  body_entries: BodyEntries;
  config: Config;
  library_items: LibraryItems;
  list_items: ListItems;
  log_entries: LogEntries;
  programs: Programs;
  refused_writes: RefusedWrites;
  row_history: RowHistory;
  stretch_weeks: StretchWeeks;
  supplement_days: SupplementDays;
  users: Users;
  weeks: Weeks;
}
